### ISSUE TITLE
[FEATURE]: download wallpaper repo's

### ISSUE THREAD

**Issue by dianaw353** [dianaw353/dotfiles#18]
**Description**
Allow user to choose a repo containing wallpaper and download a repo containing wallpapers

**Comment by kurtbahartr** [comment]
Handled using GitHub APIs without cloning the repo itself here: https://github.com/dianaw353/dotfiles/blob/40bbadbb98bf66b2c7dd19a597302720ccea8e8e/roles/ags/tasks/main.yml#L164-L173
