### ISSUE TITLE
[BUG] Hyprpm requires Hyprland to run

### ISSUE THREAD

**Issue by kurtbahartr** [dianaw353/dotfiles#27]
**Describe the bug**
Hyprpm requires Hyprland to run to get symbols and do anything at all. Trying to perform the Playbook without running Hyprland first causes a weird Git error.

**To Reproduce**
1. Run the Playbook without having run Hyprland before at all (E.g. a completely clean Arch installation).

**Expected behavior**
The Playbook runs just fine and goes on with Hyprland steps as well.

**Screenshots**
N/A

**Distribution:**
Arch Linux

**Additional context**
- The fastest and easiest way to reproduce this and test potential fixes is to perform a minimal Arch installation.
- This error can be worked around by starting Hyprland after the fail and continuing from there.

**Comment by dianaw353** [comment]
I will need to look into this and find a solution

**Comment by kurtbahartr** [comment]
I have an idea!

How about we do it this way, considering only dynamic cursors addon is installed using `hyprpm`?

1. Move hyprpm stuff to a different role entirely, preferably under post-config phase, independent from `roles` variable.
2. Enable `hyprpm update` step.
3. Require Hyprland to be running for the role to be included, skip otherwise.
4. Add an optional installation step after main `ansible-playbook` in the README for something like this;
> If you want animated dynamic cursors, you have to execute the corresponding role manually after booting up to Hyprland;
> ```
> ansible-playbook main.yml --ask-become-pass -t hypraddons
> ```

EDIT: Or, even better, handle it at Hyprland startup! Recycle the way Bluetooth Manager TUI is run, cramp it into a startup script, have the startup config run and delete itself once it's done!

**Comment by kurtbahartr** [comment]
Done the first part of the aforementioned implementation with the role called "hyprpm".

https://github.com/dianaw353/dotfiles/commit/caa1b4372dff7f3f488daa2acbf0bc8dc22c1c48
