### ISSUE TITLE
[BUG] `bluetuith-bin` is placed in the incorrect section of AGS package installations

### ISSUE THREAD

**Issue by kurtbahartr** [dianaw353/dotfiles#31]
**Describe the bug**
`bluetuith-bin` in AGS dependencies has to be moved to the AUR section since it's not on official Arch repos.

**To Reproduce**
1. Do an Arch installation in the most minimal way physically possible.
2. Go through the dotfiles setup process. Running `ansible-playbook` in `--check` mode will save you from an incomplete state.

**Expected behavior**
The checking/installing process goes smoothly.

**Screenshots**
N/A

**Distribution (please complete the following information):**
Arch Linux

**Additional context**
N/A

**Comment by kurtbahartr** [comment]
I might open a PR for this pretty soon.

**Comment by kurtbahartr** [comment]
I just noticed the other packages I mentioned were already added before, it was the `--check` mode that was failing. I'll open the PR only with the `bluetuith-bin` change.

**Comment by dianaw353** [comment]
Provied a different fix here [c4fd8a2](https://github.com/dianaw353/dotfiles/commit/c4fd8a24303b51df125096c68e6462908e34168e)
