### ISSUE TITLE
[FEATURE] Add notitification that battery is low

### ISSUE THREAD

**Issue by dianaw353** [dianaw353/dotfiles#57]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by kurtbahartr** [comment]
To anyone concerned: This one was quickly bodged into rolling release with `batsignal`. However, we did that just because v1 is now superseded. We'll make something native to Astal and drop batsignal once we do the migration to AGSv2.
