### ISSUE TITLE
[FEATURE]: Keyboard shortcut window

### ISSUE THREAD

**Issue by dianaw353** [dianaw353/dotfiles#9]
**Description**
Adds a window to view what keyboard shortcuts are there

**Comment by kurtbahartr** [comment]
I guess we can fork and rename [pardus-gnome-shortcuts](https://github.com/pardus/pardus-gnome-shortcuts) and make it work with Hyprland configurations for this?

**Comment by dianaw353** [comment]
I would like to integrate it w/ AGS and not need another dependency

**Comment by kurtbahartr** [comment]
That sounds like a far better idea. I forgot you can do pretty much anything many Pardus apps can do with AGS' built-in functions. 😅
